### ISSUE TITLE
the months are the same in the southern hemisphere, just the seasons are different.

### ISSUE THREAD

**Issue by dominictarr** [videlalvaro/gifsockets#1]
just sayin'

**Comment by videlalvaro** [comment]
Dude… I'm from Uruguay but I live in the North Hemisphere. Considering that people can't believe when I say that we have summer in December and January. Can you imagine that? Christmas in Summer along the beach? Oh yes. Sometimes people can't believe that at first.

Anyway… have a good weekend

**Comment by mattsoutherden** [comment]
I read the README and thought "I should open a ticket to point that out". Too slow, as usual.

**Comment by TEHEK** [comment]
I did submit a pull request, but there was nobody to merge it.

This is me @videlalvaro editing your comment. I think @github shouldn't allow this.

**Comment by thoughtless** [comment]
It's a joke.

**Comment by videlalvaro** [comment]
@thoughtless finally someone realises!
