### ISSUE TITLE
IllegalArgument

### ISSUE THREAD

**Issue by astanway** [videlalvaro/gifsockets#3]
Upon running (def encoder (create-gif (.getOutputStream client))) in the REPL:

IllegalArgumentException No matching field found: getOutputStream for class clojure.lang.Var$Unbound  clojure.lang.Reflector.getInstanceField (Reflector.java:271)

**Comment by videlalvaro** [comment]
You need to first open the page in the browser before creating the encoder. the `Unbound` is the key there. You don't have a object that responds to `getOutputStream` because there's no output stream without a client connected
