### ISSUE TITLE
Javascript client

### ISSUE THREAD

**Issue by jcubic** [videlalvaro/gifsockets#5]
Do you have javascript client for this? Can it be used to create something like sockets but without the need to bind to new port (only 80)?

**Comment by Heath123** [comment]
I know I'm 6 years years late but WebSockets (or HTTP longpolling) should run on port 80 anyway

**Comment by jcubic** [comment]
Web socket usually run on different port since you can have websocket and web server run on same physical server. If 80 is taken by web server you can't run web sockets on port 80.

**Comment by Heath123** [comment]
You can run a Websocket server and a HTTP server on the same port

**Comment by Heath123** [comment]
https://stackoverflow.com/questions/29497725/can-websockets-and-http-server-both-run-on-the-same-port-number

**Comment by Heath123** [comment]
HTTP servers should hopefully already support this, but if you're willing to write custom code, you can run almost any service on the same port :)

**Comment by jcubic** [comment]
I don't think you're correct, Websocket don't run over HTTP so you would need to have two different servers HTTP and Websockets merged into one server, so in fact you will need HTTPWebSocketServer not sure if something like this exists.

It would be no easy to create because every single server is for single protocol. Do you have any example of Multi protocol Server?

**Comment by Heath123** [comment]
@jcubic Websocket literally does go over HTTP though, that’s the entire point

**Comment by Heath123** [comment]
And if you look into raw TCP sockets each communication usually starts with a handshake, so you can switch which protocol you use based on that handshake, I’ll send an example soon

**Comment by jcubic** [comment]
@Heath123 it don't run over HTTP it's only compatible with HTTP, to make it the same server you would need to create HTTP proxy. But if you have example of having single HTTP server that have both normal HTTP and websockets that would be awesome, but I don't think it's possible.

**Comment by Heath123** [comment]
@jcubic I already linked it at https://stackoverflow.com/questions/29497725/can-websockets-and-http-server-both-run-on-the-same-port-number

**Comment by Heath123** [comment]
That's actually quite a common and supported thing to do I think

**Comment by Heath123** [comment]
And here's an example with incompatible protocols:
https://stackoverflow.com/questions/22453782/nodejs-http-and-https-over-same-port

**Comment by Heath123** [comment]
You can just Google "HTTP and Websocket on same port [your favourite programming language]"

**Comment by jcubic** [comment]
That SO answer is not the same as running two servers on same port, it's just redirect to different port it's not the same as running two services on same port. And second edited answers binds 3 ports this so it's not single port.

In my case I don't want to run anything on different port, because my shared hosting don't allow this. For my I don't think it's possible to have two services on same port.

**Comment by videlalvaro** [comment]
See the linked answer here
https://stackoverflow.com/questions/13791050/is-it-possible-to-enable-tcp-http-and-websocket-all-using-the-same-port

Basically what you need is a way to detect on port 80 let's say, what
protocol the client wishes to talk. This can be done with a proxy server or
something. Then behind that proxy server you will have two distinct
services running either HTTP or Websockets, using an internal port. The
Proxy will just detect the protocol and forward to either of those services.

Is that what your hosting provider allows you to do? That's a different
technical question

**Comment by Heath123** [comment]
> That SO answer is not the same as running two servers on same port, it's just redirect to different port it's not the same as running two services on same port. And second edited answers binds 3 ports this so it's not single port.
> 
> In my case I don't want to run anything on different port, because my shared hosting don't allow this. For my I don't think it's possible to have two services on same port.

But it has the same effect, you could also serve both in the same process, it's just easier to redirect it
Anyway it's just an example, you absolutely can serve Websocket and HTTP on the same server really easily

**Comment by Heath123** [comment]
Example: https://repl.it/@HeathMitchell1/remotecontrol#index.js

**Comment by Heath123** [comment]
It serves both a site and a Websocket on port 8080

**Comment by Heath123** [comment]
It's this simple:
```js
const https = require('http');
const WebSocket = require('ws');

const server = https.createServer({});
const wss = new WebSocket.Server({ server });
```
You do know that this repo is a joke, right? Even if you can't use Websocket a much more practical solution is [HTTP longpolling](https://www.pubnub.com/blog/http-long-polling/)

**Comment by Heath123** [comment]
https://www.ably.io/blog/websockets-vs-long-polling

**Comment by videlalvaro** [comment]
closing since this is offtopic to gifsockets
